NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GBMESA6JZO5EUPAJDIRJP76KZUPVTL3KQA3I4YQ7Z44E4SVTV7IBMU5Q"
]
VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME="Spicy Token"
ORG_URL="https://www.spicytoken.org"
ORG_DESCRIPTION="By helping developers, liquidity providers, and traders, Spicy enables all members of the financial ecosystem to take part in a liquid marketplace."
ORG_TWITTER="@SpicyToken"
ORG_LOGO="https://i.ibb.co/HqVLWm3/spicy-logo.png"
ORG_OFFICIAL_EMAIL="spicytkn@gmail.com"


[[CURRENCIES]]
code="xspc"
issuer="GBMESA6JZO5EUPAJDIRJP76KZUPVTL3KQA3I4YQ7Z44E4SVTV7IBMU5Q"
anchor_asset="false"
name="Spicy Token"
desc="Spicy is a shared network for cross-chain communication connecting multiple blockchains into one unified network. This currency gives the ability to buy tokens at a low price and it rises up with every transaction made inside this chain due to the fact that it is interconnected with the Stellar network."
image="https://i.ibb.co/HqVLWm3/spicy-logo.png"
fixed_number=1000000
max_number=1000000
is_unlimited=false
#SpicyToken was issued using the open and inclusive Stellar blockchain network.
